version: "3.8"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: ids_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # ClickHouse's official image auto-runs any .sql file placed here
      # on first startup - this loads your schema automatically.
      - ./clickhouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - CLICKHOUSE_DB=siem
      - CLICKHOUSE_USER=siem_user
      - CLICKHOUSE_PASSWORD=changeme

  zeek:
    build: ./zeek
    container_name: ids_zeek
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./zeek/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek:ro
      - ./zeek/signatures:/usr/local/zeek/share/zeek/site/signatures:ro
      - ./pcaps:/pcaps:ro
      - zeek_logs:/usr/local/zeek/logs
    environment:
      - MODE=pcap
      - PCAP_FILE=/pcaps/sample.pcap
    depends_on:
      clickhouse:
        condition: service_started

  ingest:
    build: ./ingest
    container_name: ids_ingest
    volumes:
      - zeek_logs:/usr/local/zeek/logs:ro
    environment:
      - ZEEK_LOG_DIR=/usr/local/zeek/logs
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=siem_user
      - CLICKHOUSE_PASSWORD=changeme
      - CLICKHOUSE_DB=siem
    depends_on:
      clickhouse:
        condition: service_started

  cve-matcher:
    build: ./cve
    container_name: ids_cve_matcher
    volumes:
      - ./cve/cve_data:/cve_data
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=siem_user
      - CLICKHOUSE_PASSWORD=changeme
      - CLICKHOUSE_DB=siem
      - POLL_INTERVAL_SECONDS=30
    depends_on:
      clickhouse:
        condition: service_started

  dashboard:
    build: ./dashboard
    container_name: ids_dashboard
    ports:
      - "8501:8501"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=siem_user
      - CLICKHOUSE_PASSWORD=changeme
      - CLICKHOUSE_DB=siem
    depends_on:
      clickhouse:
        condition: service_started

volumes:
  zeek_logs:
  clickhouse_data:
